version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: pry-byebug
        versions:
        - ">= 3.10"
      - dependency-name: rails
        versions:
        - ">= 6"
      - dependency-name: spring
        versions:
        - ">= 2.2"
      - dependency-name: spring-watcher-listen
        versions:
        - ">= 2.1"
    groups:
      rubocop:
        patterns:
          - "rubocop*"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: exports-loader
        versions:
        - ">= 2"
      - dependency-name: bootstrap
        versions:
        - ">= 5"
      - dependency-name: minimatch
        versions:
        - ">= 10"
      - dependency-name: stylelint
        versions:
        - ">= 16"
      - dependency-name: stylelint-config-twbs-bootstrap
        versions:
        - ">= 13"
      - dependency-name: stylelint-order
        versions:
        - ">= 7"
      - dependency-name: stylelint-scss
        versions:
        - ">= 6"
      - dependency-name: stylelint-webpack-plugin
        versions:
        - ">= 3"
      - dependency-name: webpack
        versions:
        - ">= 5"
      - dependency-name: webpack-cli
        versions:
        - ">= 4"
      - dependency-name: webpack-dev-server
        versions:
        - ">= 4"
    groups:
      babel:
        patterns:
          - "@babel/*"
      fontawesome:
        patterns:
          - "@fortawesome/*"
      rails:
        patterns:
          - "@rails/*"
      webpack:
        patterns:
          - "webpack*"
