require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/requests/**/*'
    - 'spec/system/**/*'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
